[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr = "bb48c4e66dcf7025380e714c7c600145cd049de73e536c32e984e4ac96c6c7bb"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
